name: kwalu_selli
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.3.4'


dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  auto_route: ^5.0.1
  bloc: ^8.0.2
  bloc_test: ^9.1.0
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flex_color_scheme: ^6.0.1
  http_mock_adapter: ^0.3.3
  google_fonts: ^3.0.1
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_native_splash: ^2.2.11
  flutter_secure_storage: ^6.0.0
  freezed_annotation: ^2.1.0
  shared_preferences: ^2.0.15
  injectable: ^1.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.2
  build_runner: ^2.3.0
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  mocktail: ^0.3.0
  moor_generator: ^4.6.0+1


flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/gif/